[package]
name = "vart"
publish = true
version = "0.9.3"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
description = "An immutable versioned adaptive radix trie."
repository = "https://github.com/surrealdb/vart"
homepage = "https://github.com/surrealdb/vart"
documentation = "https://docs.rs/vart/"
keywords = [
    "trie",
    "immutable-trie",
    "snapshot-isolation",
    "adaptive-radix-trie",
    "radix-trie",
]

[dependencies]

[dev-dependencies]
rand = "0.8.5"
criterion = "0.5.1"
divan = "0.1.14"

[[bench]]
name = "vart_bench"
path = "benches/vart_bench.rs"
harness = false

[[bench]]
name = "allocs"
path = "benches/allocs.rs"
harness = false

[lints.clippy]
allow_attributes = "allow"
assigning_clones = "warn"
bool_assert_comparison = "allow"
clone_on_ref_ptr = "warn"
cloned_instead_of_copied = "warn"
debug_assert_with_mut_call = "warn"
disallowed_methods = "warn"
expl_impl_clone_on_copy = "warn"
explicit_into_iter_loop = "warn"
fallible_impl_from = "warn"
get_unwrap = "warn"
implicit_clone = "warn"
inefficient_to_string = "warn"
large_types_passed_by_value = "warn"
lossy_float_literal = "warn"
mutex_atomic = "warn"
no_effect_underscore_binding = "warn"
option_as_ref_cloned = "warn"
redundant_clone = "warn"
ref_option_ref = "warn"
set_contains_or_insert = "warn"
single_char_pattern = "warn"
trivially_copy_pass_by_ref = "warn"
unnecessary_to_owned = "warn"
unwrap_used = "allow"
used_underscore_binding = "warn"
