# Configuration documentation:
#   https://embarkstudios.github.io/cargo-deny/index.html

[advisories]
yanked = "deny"
ignore = [
]
git-fetch-with-cli = true

[licenses]
allow = ["Apache-2.0"]
confidence-threshold = 0.8


[bans]
multiple-versions = "warn"
highlight = "all"
