name: CI

run-name: "CI run '${{ github.head_ref || github.ref_name }}'"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - next
  pull_request:
  merge_group:

defaults:
  run:
    shell: bash

jobs:
  ci:
    strategy:
      matrix:
        os: ["ubuntu-latest"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-deny
        run: cargo install --debug --locked cargo-deny@0.15.1 || true

      - name: Compile
        run: cargo build --all-targets --all-features

      - name: Run tests
        run: make test

      - name: Clippy
        run: cargo clippy --all --all-targets -- -D warnings

      - name: Format
        run: cargo fmt --all -- --check

  semver:
    name: semver
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
